services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - api-workspace:/workspace:nocopy
    working_dir: /workspace
    command: sleep infinity
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: development
      POSTGRES_HOST: db
      RAILS_ENV: development
    ports:
      - "3000:3000"

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: development
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
  api-workspace: